"""Narrative structure catalog.

Pasted verbatim from the product spec. Each entry defines one rhetorical structure
(SCQA, Pyramid, BLUF, ...) used by the outline_creator subagent to shape the deck.
"""

from typing import Any

STRUCTURE_DEFINITIONS: dict[str, dict[str, Any]] = {
    "scqa": {
        "id": "scqa",
        "name_en": "SCQA",
        "name_zh": "SCQA",
        "description_en": "Situation-Complication-Question-Answer narrative for diagnosing and solving problems.",
        "description_zh": "情境-冲突-问题-答案结构，适合问题诊断与解决方案表达。",
        "tone_en": "Executive and diagnostic.",
        "tone_zh": "理性诊断、结论导向。",
        "focus_en": "Clarify context, expose tension, converge to a concrete answer.",
        "focus_zh": "先讲背景与冲突，再收敛到可执行答案。",
        "evidence_en": "Business facts, root-cause signals, and option trade-offs.",
        "evidence_zh": "业务事实、根因信号与方案取舍。",
        "slide_mix_en": "Open with context, then conflict and key question, then recommendation and action plan.",
        "slide_mix_zh": "先背景后冲突与关键问题，最后给出方案与行动路径。",
    },
    "pyramid": {
        "id": "pyramid",
        "name_en": "Pyramid",
        "name_zh": "金字塔",
        "description_en": "Answer-first structure with layered supporting arguments.",
        "description_zh": "结论先行，再分层展开支撑论点。",
        "tone_en": "Authoritative and concise.",
        "tone_zh": "权威、简洁、结构化。",
        "focus_en": "Lead with conclusion, then MECE evidence clusters.",
        "focus_zh": "先结论，再用 MECE 论据分组支撑。",
        "evidence_en": "Top-down claims, data-backed sub-arguments, and implication synthesis.",
        "evidence_zh": "自上而下主张、数据支撑分论点、最终归纳影响。",
        "slide_mix_en": "Cover -> key conclusion -> 3-4 argument blocks -> implications -> closing actions.",
        "slide_mix_zh": "封面 -> 核心结论 -> 3-4 组支撑论点 -> 影响归纳 -> 行动收束。",
    },
    "bluf": {
        "id": "bluf",
        "name_en": "BLUF",
        "name_zh": "BLUF",
        "description_en": "Bottom Line Up Front for high-pressure executive communication.",
        "description_zh": "先讲底线结论，适合高压高管沟通。",
        "tone_en": "Direct and high-signal.",
        "tone_zh": "直接、高信噪比。",
        "focus_en": "Deliver decision-ready bottom line first, then only essential proof.",
        "focus_zh": "先给可决策结论，再补充最关键证据。",
        "evidence_en": "One-page summary logic, impact numbers, and immediate asks.",
        "evidence_zh": "一页摘要逻辑、关键影响数字与明确请求。",
        "slide_mix_en": "Immediate conclusion slide, then short justification, risks, and ask/next step.",
        "slide_mix_zh": "首屏即结论，随后简要论证、风险与下一步请求。",
    },
    "problem_solution": {
        "id": "problem_solution",
        "name_en": "Problem-Solution",
        "name_zh": "问题-方案",
        "description_en": "Frame pain points clearly and map to actionable solutions.",
        "description_zh": "明确问题痛点并映射到可执行方案。",
        "tone_en": "Pragmatic and action-oriented.",
        "tone_zh": "务实、执行导向。",
        "focus_en": "Define problem severity, propose solution architecture, and implementation path.",
        "focus_zh": "界定问题严重性，提出方案框架与落地路径。",
        "evidence_en": "Current-state symptoms, quantified impact, and solution feasibility.",
        "evidence_zh": "现状症状、量化影响与方案可行性。",
        "slide_mix_en": "Problem diagnosis -> solution design -> rollout roadmap -> expected impact.",
        "slide_mix_zh": "问题诊断 -> 方案设计 -> 推进路线 -> 预期收益。",
    },
    "chronological": {
        "id": "chronological",
        "name_en": "Chronological",
        "name_zh": "时间序列",
        "description_en": "Past-present-future storyline for reviews and planning.",
        "description_zh": "按过去-现在-未来组织，适合复盘与规划。",
        "tone_en": "Narrative and traceable.",
        "tone_zh": "叙事清晰、过程可追溯。",
        "focus_en": "Show event evolution and derive next-stage recommendations.",
        "focus_zh": "展示事件演进并推导下一阶段建议。",
        "evidence_en": "Milestones, timeline inflections, and future commitments.",
        "evidence_zh": "关键里程碑、阶段拐点与后续承诺。",
        "slide_mix_en": "History baseline -> current status -> turning points -> future plan.",
        "slide_mix_zh": "历史基线 -> 现状评估 -> 拐点总结 -> 未来计划。",
    },
    "fivew2h": {
        "id": "fivew2h",
        "name_en": "5W2H",
        "name_zh": "5W2H",
        "description_en": "Operational decomposition by What/Why/Who/When/Where/How/How much.",
        "description_zh": "按 What/Why/Who/When/Where/How/How much 拆解执行问题。",
        "tone_en": "Operational and complete.",
        "tone_zh": "全面、执行细化。",
        "focus_en": "Ensure no critical execution dimension is missed.",
        "focus_zh": "确保执行信息覆盖无死角。",
        "evidence_en": "Ownership clarity, timelines, resources, and budget impacts.",
        "evidence_zh": "责任归属、时间计划、资源投入与预算影响。",
        "slide_mix_en": "Frame objective -> 5W2H decomposition -> dependencies -> execution checklist.",
        "slide_mix_zh": "目标定义 -> 5W2H 分解 -> 依赖关系 -> 执行清单。",
    },
    "what_so_what_now_what": {
        "id": "what_so_what_now_what",
        "name_en": "What-SoWhat-NowWhat",
        "name_zh": "是什么-意味着什么-下一步",
        "description_en": "Translate data observations into business implications and actions.",
        "description_zh": "把数据观察转化为业务含义与行动建议。",
        "tone_en": "Analytical and recommendation-driven.",
        "tone_zh": "分析型、建议导向。",
        "focus_en": "Move from facts to implications to concrete interventions.",
        "focus_zh": "从事实到影响再到具体干预动作。",
        "evidence_en": "Metrics trend, business impact estimate, and intervention ROI.",
        "evidence_zh": "指标趋势、业务影响估算与干预收益。",
        "slide_mix_en": "What happened -> why it matters -> what to do next.",
        "slide_mix_zh": "先讲发生了什么 -> 再讲为什么重要 -> 最后讲怎么做。",
    },
    "pas": {
        "id": "pas",
        "name_en": "PAS",
        "name_zh": "PAS",
        "description_en": "Problem-Agitate-Solution persuasion pattern for conversion-oriented storytelling.",
        "description_zh": "问题-放大-解决结构，适合转化导向叙事。",
        "tone_en": "Persuasive and urgency-driven.",
        "tone_zh": "说服性强、强调紧迫感。",
        "focus_en": "Surface pain, amplify consequence, then present solution with clear payoff.",
        "focus_zh": "先指出痛点并放大后果，再呈现解决方案与收益。",
        "evidence_en": "Loss scenarios, urgency metrics, and before/after evidence.",
        "evidence_zh": "损失场景、紧迫度指标与前后对比证据。",
        "slide_mix_en": "Pain point -> consequence escalation -> solution offer -> conversion action.",
        "slide_mix_zh": "痛点 -> 后果放大 -> 方案呈现 -> 转化行动。",
    },
    "aida": {
        "id": "aida",
        "name_en": "AIDA",
        "name_zh": "AIDA",
        "description_en": "Attention-Interest-Desire-Action sequence for pitches and campaigns.",
        "description_zh": "注意-兴趣-欲望-行动序列，适合提案与营销场景。",
        "tone_en": "Commercial and momentum-building.",
        "tone_zh": "营销导向、节奏递进。",
        "focus_en": "Capture attention quickly and drive clear call-to-action.",
        "focus_zh": "快速吸引注意并推动明确行动。",
        "evidence_en": "Hooks, audience resonance points, value proof, and CTA specificity.",
        "evidence_zh": "抓手信息、受众共鸣点、价值证据与明确 CTA。",
        "slide_mix_en": "Hook -> audience relevance -> value proof -> action close.",
        "slide_mix_zh": "吸引注意 -> 关联兴趣 -> 价值证明 -> 行动收束。",
    },
    "hero_journey": {
        "id": "hero_journey",
        "name_en": "Hero Journey",
        "name_zh": "英雄之旅",
        "description_en": "Transformational narrative with audience/customer as the hero.",
        "description_zh": "以受众/客户为主角的转型叙事结构。",
        "tone_en": "Inspirational and emotionally resonant.",
        "tone_zh": "愿景化、情感共鸣。",
        "focus_en": "Contrast old world vs new world and position solution as enabling guide.",
        "focus_zh": "对比旧世界与新世界，强调方案的赋能角色。",
        "evidence_en": "Story beats, turning moments, and tangible outcome vision.",
        "evidence_zh": "故事节点、关键转折与可感知愿景结果。",
        "slide_mix_en": "Current struggle -> call to change -> guide/tool -> transformed future.",
        "slide_mix_zh": "当前困境 -> 变革召唤 -> 导师/工具 -> 未来新常态。",
    },
    "gallery": {
        "id": "gallery",
        "name_en": "Gallery",
        "name_zh": "图集相册",
        "description_en": "Album and picture-gallery structure for image-led storytelling.",
        "description_zh": "面向相册、图集与视觉记录的图片主导型叙事结构。",
        "tone_en": "Visual, editorial, and lightly contextual.",
        "tone_zh": "视觉优先、编辑感强、少量语境说明。",
        "focus_en": "Present one strong image moment or a curated set of related images on each slide.",
        "focus_zh": "每页呈现一个核心影像瞬间，或一组经过策展的相关图片。",
        "evidence_en": "Captions, scene context, source notes, dates, locations, and thematic tags.",
        "evidence_zh": "图片说明、场景语境、来源备注、日期、地点与主题标签。",
        "slide_mix_en": (
            "Cover -> collection overview -> image feature spreads -> multi-image gallery "
            "grids -> closing summary."
        ),
        "slide_mix_zh": "封面 -> 图集概览 -> 单图重点页 -> 多图网格页 -> 总结收束。",
    },
    "grouping": {
        "id": "grouping",
        "name_en": "Grouping (Legacy)",
        "name_zh": "分组结构（兼容）",
        "description_en": "Legacy grouping structure retained for old projects.",
        "description_zh": "为历史项目保留的分组结构。",
        "tone_en": "Neutral and categorized.",
        "tone_zh": "中性分组。",
        "focus_en": "Group related ideas under coherent clusters.",
        "focus_zh": "把相关观点按主题分组呈现。",
        "evidence_en": "Category-level facts and grouped support points.",
        "evidence_zh": "分组事实与主题支撑点。",
        "slide_mix_en": "Topic group overview -> grouped evidence -> synthesized takeaway.",
        "slide_mix_zh": "主题分组概览 -> 分组证据 -> 综合结论。",
        "legacy": True,
    },
}


def get_structure(structure_id: str) -> dict[str, Any]:
    if structure_id not in STRUCTURE_DEFINITIONS:
        raise KeyError(f"Unknown structure_id: {structure_id}")
    return STRUCTURE_DEFINITIONS[structure_id]


def list_structures(include_legacy: bool = False) -> list[dict[str, Any]]:
    return [s for s in STRUCTURE_DEFINITIONS.values() if include_legacy or not s.get("legacy")]
